# Generated by Django 5.1 on 2025-12-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlekm",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="saidaestoque",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="saidaestoque",
            name="os_servico",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="BaixaEstoque",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200, verbose_name="Nome do Item")),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "descricao_servico",
                    models.TextField(verbose_name="O que foi feito?"),
                ),
                (
                    "pecas_usadas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Peças/Materiais Usados"
                    ),
                ),
                (
                    "km_percorrida",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="KM Percorrida (Opcional)"
                    ),
                ),
                (
                    "assinatura",
                    models.ImageField(
                        blank=True, null=True, upload_to="assinaturas_os/"
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
